### ISSUE TITLE
Issues with the network

### ISSUE THREAD

**Issue by ofirkris** [fenglinglwb/MAT#19]
Thanks for sharing your great work!

I'm researching image inpainting solutions and find MAT the best i've seen so far, though there are some issues I'd like to point:
1. Network only supports square 512px input image - while other solutions like Lama support any image aspect ratio
2. Face model doesn't give any output only Places model works.

**Comment by fenglinglwb** [comment]
Thanks for your interest in our work.
1. As clarified, you need to make the size of an input image a multiple of 512, e.g., 512x512 or 1024x1024. Indeed this needs improvement. Thanks for your advice.
2. I have tested both the CelebA-512 and CelebA-256 models. They all worked. If you refer to the CelebA-256 model, you need to specify the resolution as 256. Could you try again or point out where raises errors?

**Comment by ofirkris** [comment]
1. Did that. adding whitespace on edges on non square images won't confuse model to complete white area?
![celeba1](https://user-images.githubusercontent.com/9070477/175834822-ee96f317-ac8f-46e7-8f47-aea3f58ddc05.jpeg)
2. celeb 512 doesn't work - do I need to add some parameters? image attached

**Comment by fenglinglwb** [comment]
1. Most existing models are trained with aligned face images (only faces without other human bodies). If processing the shown image, you need to perform the face alignment so that the model won't be confused.
2. I have retried CelebA-512 model. It successfully produced outputs. Please find the images attached. Besides, could you please provide the full running log?
<img width="519" alt="image" src="https://user-images.githubusercontent.com/12084739/175848560-7055287b-faae-4f7e-b5d2-4da5228adf92.png">
<img width="291" alt="image" src="https://user-images.githubusercontent.com/12084739/175848591-1f18c3e9-b503-4a0b-9763-093f7ce91bb6.png">

**Comment by 12op** [comment]
您好,我使用您 CelebA-512 模型进行测试时，没有输出结果，只产生了空文件夹，这个怎么解决呢

**Comment by 12op** [comment]
When using celeba-512 model test, there is no output result, only empty folder. How to solve this？

**Comment by fenglinglwb** [comment]
Our logic now only supports '.jpg' and '.png‘. Have you checked whether the input image is successfully read?
